app/urls.py
from django.urls import path
from app.views import *
from app.views.categoria.views import *
from app.views.marca.views import *
from app.views.presentacion.views import *
from app.views.producto.views import *
from app.views.cliente.views import *
from app.views.mesero.views import *
from app.views.plato.views import *
from app.views.administrador.views import *
from app.views.operador.views import *
from app.views.venta.views import *
from app.views.detalle_venta.views import *
from app.views.cuenta.views import *
from app.views.reportes.viewsExcel import *
from app.views.reportes.viewsPDF import *
from app.views.reportes.views import *
from backups.views import BackupDatabaseView, RestoreDatabaseView, DeleteBackupView, BackupListView

app_name = 'app'
urlpatterns = [
    ### CRUD CATEGORÍA ###
    path('categoria/listar/', CategoriaListView.as_view(), name='categoria_lista'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria_crear'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_editar'),
    path('categoria/eliminar/<int:pk>/', CategoriaDeleteView.as_view(), name='categoria_eliminar'),

    ### CRUD MARCA ###
    path('marca/listar/', MarcaListView.as_view(), name='marca_lista'),
    path('marca/crear/', MarcaCreateView.as_view(), name='marca_crear'),
    path('marca/editar/<int:pk>/', MarcaUpdateView.as_view(), name='marca_editar'),
    path('marca/eliminar/<int:pk>/', MarcaDeleteView.as_view(), name='marca_eliminar'),

    ### CRUD PRESENTACIÓN ###
    path('presentacion/listar/', PresentacionListView.as_view(), name='presentacion_lista'),
    path('presentacion/crear/', PresentacionCreateView.as_view(), name='presentacion_crear'),
    path('presentacion/editar/<int:pk>/', PresentacionUpdateView.as_view(), name='presentacion_editar'),
    path('presentacion/eliminar/<int:pk>/', PresentacionDeleteView.as_view(), name='presentacion_eliminar'),

    ### CRUD PRODUCTO ###
    path('producto/listar/', ProductoListView.as_view(), name='producto_lista'),
    path('producto/crear/', ProductoCreateView.as_view(), name='producto_crear'),
    path('producto/editar/<int:pk>/', ProductoUpdateView.as_view(), name='producto_editar'),
    path('producto/eliminar/<int:pk>/', ProductoDeleteView.as_view(), name='producto_eliminar'),

    ### CRUD CLIENTE ###
    path('cliente/listar/', ClienteListView.as_view(), name='cliente_lista'),
    path('cliente/crear/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('cliente/editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editar'),
    path('cliente/eliminar/<int:pk>/', ClienteDeleteView.as_view(), name='cliente_eliminar'),
    
    ### CRUD MESERO ###
    path('mesero/listar/', MeseroListView.as_view(), name='mesero_lista'),
    path('mesero/crear/', MeseroCreateView.as_view(), name='mesero_crear'),
    path('mesero/editar/<int:pk>/', MeseroUpdateView.as_view(), name='mesero_editar'),
    path('mesero/eliminar/<int:pk>/', MeseroDeleteView.as_view(), name='mesero_eliminar'),

    ### CRUD PLATO ###
    path('plato/listar/', PlatoListView.as_view(), name='plato_lista'),
    path('plato/crear/', PlatoCreateView.as_view(), name='plato_crear'),
    path('plato/editar/<int:pk>/', PlatoUpdateView.as_view(), name='plato_editar'),
    path('plato/eliminar/<int:pk>/', PlatoDeleteView.as_view(), name='plato_eliminar'),
    
    ### CRUD ADMINISTRADOR ###
    path('administrador/listar/', AdministradorListView.as_view(), name='administrador_lista'),
    path('administrador/crear/', AdministradorCreateView.as_view(), name='administrador_crear'),
    path('administrador/editar/<int:pk>/', AdministradorUpdateView.as_view(), name='administrador_editar'),
    path('administrador/eliminar/<int:pk>/', AdministradorDeleteView.as_view(), name='administrador_eliminar'),

    ### CRUD OPERADOR ###
    path('operador/listar/', OperadorListView.as_view(), name='operador_lista'),
    path('operador/crear/', OperadorCreateView.as_view(), name='operador_crear'),
    path('operador/editar/<int:pk>/', OperadorUpdateView.as_view(), name='operador_editar'),
    path('operador/eliminar/<int:pk>/', OperadorDeleteView.as_view(), name='operador_eliminar'),
    
    ### CRUD VENTA ###
    path('venta/listar/', VentaListView.as_view(), name='venta_lista'),
    path('venta/crear/', VentaCreateView.as_view(), name='venta_crear'),
    path('venta/editar/<int:pk>/', VentaUpdateView.as_view(), name='venta_editar'),
    path('venta/eliminar/<int:pk>/', VentaDeleteView.as_view(), name='venta_eliminar'),
    path('venta/opciones/', ventas_view, name='venta_opciones'),

    ### DETALLE VENTA ###
    path('detalle_venta/listar/', DetalleVentaListView.as_view(), name='detalle_venta_lista'),
    path('detalleventa/eliminar/<int:pk>/', DetalleVentaDeleteView.as_view(), name='detalle_venta_eliminar'),

    ### CUENTA ###
    path('cuenta/listar/', CuentaListView.as_view(), name='cuenta_lista'),
    path('cuenta/crear/', CuentaCreateView.as_view(), name='cuenta'),

    ### COPIA DE SEGURIDAD DE BASE DE DATOS ###
    path('gestionar_backups/', BackupDatabaseView.as_view(), name='gestionar_backups'),
    path('restaurar_backup/', RestoreDatabaseView.as_view(), name='restaurar_backup'),
    path('eliminar-backup/', DeleteBackupView.as_view(), name='eliminar_backup'),
    path('backup_list/', BackupListView.as_view(), name='backup_list'),

    ### REPORTES ###
    path('gestion_reportes/', reporte_selector, name='gestion_reportes'),
    path('reportes/categorias/excel/', export_categorias_excel, name='export_categorias_excel'),
    path('reportes/marcas/excel/', export_marcas_excel, name='export_marcas_excel'),
    path('reportes/presentaciones/excel/', export_presentaciones_excel, name='export_presentaciones_excel'),
    path('reportes/productos/excel/', export_productos_excel, name='export_productos_excel'),
    path('reportes/platos/excel/', export_platos_excel, name='export_platos_excel'),
    path('reportes/meseros/excel/', export_meseros_excel, name='export_meseros_excel'),
    path('reportes/clientes/excel/', export_clientes_excel, name='export_clientes_excel'),
    path('reportes/administradores/excel/', export_administradores_excel, name='export_administradores_excel'),
    path('reportes/operadores/excel/', export_operadores_excel, name='export_operadores_excel'),
    path('reportes/categorias/pdf/', export_categorias_pdf, name='export_categorias_pdf'),
    path('reportes/marcas/pdf/', export_marcas_pdf, name='export_marcas_pdf'),
    path('reportes/presentaciones/pdf/', export_presentaciones_pdf, name='export_presentaciones_pdf'),
    path('reportes/productos/pdf/', export_productos_pdf, name='export_productos_pdf'),
    path('reportes/platos/pdf/', export_platos_pdf, name='export_platos_pdf'),
    path('reportes/meseros/pdf/', export_meseros_pdf, name='export_meseros_pdf'),
    path('reportes/clientes/pdf/', export_clientes_pdf, name='export_clientes_pdf'),
    path('reportes/administradores/pdf/', export_administradores_pdf, name='export_administradores_pdf'),
    path('reportes/operadores/pdf/', export_operadores_pdf, name='export_operadores_pdf'),

        ### API´S ###
    path('venta/productos_api/', productos_api, name='productos_api'),
    path('venta/platos_api/', platos_api, name='platos_api'),
    path('venta/clientes_api/', clientes_api, name='clientes_api'),
    path('venta/meseros_api/', meseros_api, name='meseros_api'),
    path('venta/crear_cliente_ajax/', crear_cliente_ajax, name='crear_cliente_ajax'),
]

asuan/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio.views import indexView
from login.views import *
from app.views import *
from dashboard.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', indexView.as_view(), name='index'),
    path('dashboard', dashView.as_view(), name='dashboard'),
    path('login', include('login.urls')),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='register/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='register/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_confirm.html'), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'), name='password_reset_complete'),
]

backups/models.py
from django.db import models

# Create your models here.

backups/views.py
import os
import subprocess
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.http import require_POST
from django.views import View
from django.conf import settings
from datetime import datetime
from django.http import JsonResponse
from django.contrib import messages

@method_decorator(login_required, name='dispatch')
@method_decorator(never_cache, name='dispatch')
class BackupDatabaseView(View):
    @method_decorator(permission_required('app.view_backup', raise_exception=False))
    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('app.view_backup'):
            return HttpResponseRedirect(reverse('access_denied'))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        contexto = {
            'titulo': 'Gestión de bases de datos',
            'entidad': 'Gestión de bases de datos'
        }
        return render(request, 'backup.html', contexto)

    def post(self, request, *args, **kwargs):
        success = False
        try:
            db_settings = settings.DATABASES['default']
            db_name = db_settings['NAME']
            db_user = db_settings['USER']
            db_password = db_settings['PASSWORD']
            db_host = db_settings['HOST']
            db_port = db_settings['PORT']

            filename = request.POST.get('filename', f"backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.sql")
            backup_dir = os.path.join(settings.BASE_DIR, 'backups/files')
            backup_path = os.path.join(backup_dir, filename)

            os.makedirs(backup_dir, exist_ok=True)
            mysqldump_path = r"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump.exe"

            command = (
                f"\"{mysqldump_path}\" -h {db_host} -P {db_port} -u {db_user} -p{db_password} "
                f"{db_name} > \"{backup_path}\""
            )

            result = subprocess.run(command, shell=True, capture_output=True, text=True)
            if result.returncode != 0:
                messages.error(request, f"Error al crear la copia de seguridad: {result.stderr}.")
            else:
                messages.success(request, f"Copia de seguridad: {filename} creada exitosamente.")
                success = True
        except Exception as e:
            messages.error(request, f"Error al crear la copia de seguridad: {str(e)}.")

        messages_list = list(messages.get_messages(request))
        messages_str = [str(message) for message in messages_list]

        return JsonResponse({'messages': messages_str, 'success': success})

@method_decorator(login_required, name='dispatch')
@method_decorator(never_cache, name='dispatch')
class BackupListView(View):
    @method_decorator(permission_required('app.add_backup', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        try:
            backup_dir = os.path.join(settings.BASE_DIR, 'backups/files')
            files = [f for f in os.listdir(backup_dir) if f.endswith('.sql')]
            file_data = []
            for file in files:
                file_path = os.path.join(backup_dir, file)
                file_info = {
                    'filename': file,
                    'created_at': os.path.getmtime(file_path),
                    'size': os.path.getsize(file_path)
                }
                file_data.append(file_info)
            return JsonResponse({'files': file_data})
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)

@method_decorator(login_required, name='dispatch')
@method_decorator(never_cache, name='dispatch')
class RestoreDatabaseView(View):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        success = False
        try:
            filename = request.POST.get('backup_file')
            if not filename:
                raise Http404("No se especificó un archivo de respaldo.")

            if not filename.endswith('.sql'):
                raise ValueError("El archivo debe tener una extensión .sql")

            backup_dir = os.path.join(settings.BASE_DIR, 'backups/files')
            backup_path = os.path.join(backup_dir, filename)

            if not os.path.exists(backup_path):
                raise Http404("El archivo de respaldo no existe")

            db_settings = settings.DATABASES['default']
            db_name = db_settings['NAME']
            db_user = db_settings['USER']
            db_password = db_settings['PASSWORD']
            db_host = db_settings['HOST']
            db_port = db_settings['PORT']

            command = ['mysql', '-h', db_host, '-P', db_port, '-u', db_user, f"-p{db_password}", db_name]
            with open(backup_path, 'r') as input_file:
                result = subprocess.run(command, stdin=input_file, stderr=subprocess.PIPE, text=True)

            if result.returncode != 0:
                messages.error(request, f"Error al restaurar la base de datos: {result.stderr}")
            else:
                messages.success(request, f"Base de datos: {filename} restaurada correctamente.")
                success = True

        except ValueError as ve:
            messages.error(request, str(ve))
        except Exception as e:
            messages.error(request, f"Error al restaurar la base de datos: {str(e)}")

        messages_list = list(messages.get_messages(request))
        messages_str = [str(message) for message in messages_list]

        return JsonResponse({'messages': messages_str, 'success': success})

@method_decorator(login_required, name='dispatch')
@method_decorator(never_cache, name='dispatch')
class DeleteBackupView(View):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        filename = request.POST.get('filename')
        success = False
        if filename:
            file_path = os.path.join(settings.BASE_DIR, 'backups/files', filename)
            if os.path.exists(file_path):
                os.remove(file_path)
                messages.success(request, f"Copia: {filename} eliminada correctamente.")
                success = True
            else:
                messages.error(request, f"El archivo: {filename} no existe.")
        else:
            messages.error(request, "No se especificó un archivo para eliminar.")

        messages_list = list(messages.get_messages(request))
        messages_str = [str(message) for message in messages_list]

        return JsonResponse({'messages': messages_str, 'success': success})

backups/templates/backup.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
{% endblock %}
{% block contenido %}
<div class="containerBackup">
    <div class="containerTitle">
        <h1>Administración de copias de <br>seguridad de la base de datos</h1>
        <img class="img_db" src="{% static 'img/db_logo.png' %}" alt="Logo database">
    </div>
    <div class="backup-section">
        <div class="generate-section">
            <h2>Crear copia de seguridad</h2>
            <form id="backupForm" method="post" action="{% url 'app:gestionar_backups' %}"> 
                {% csrf_token %}
                <button class="btn_generate fas fa-download" type="submit"></button>
            </form>
        </div>
        <div class="restore-section">
            <h2>Restaurar copia de seguridad</h2>
            <form id="restoreForm" method="post" action="{% url 'app:restaurar_backup' %}"
                enctype="multipart/form-data">
                {% csrf_token %}
                <table id="backupTable">
                    <thead>
                        <tr>
                            <th>Nombre del archivo</th>
                            <th>Fecha de creación</th>
                            <th>Tamaño</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    <tbody id="backupList">
                    </tbody>
                </table>
                <input type="hidden" id="selectedFile" name="backup_file">
            </form>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const tableBody = document.querySelector('#backupTable tbody');

        function formatDateTime(timestamp) {
            const date = new Date(timestamp * 1000);
            return date.toLocaleString();
        }

        function loadBackupFiles() {
            fetch('{% url "app:backup_list" %}')
                .then(response => response.json())
                .then(data => {
                    if (data.error) {
                        console.error('Error:', data.error);
                        return;
                    }
                    tableBody.innerHTML = '';
                    if (data.files.length === 0) {
                        const row = document.createElement('tr');
                        row.innerHTML = `
                            <td colspan="4">No hay copias de seguridad generadas</td>
                        `;
                        tableBody.appendChild(row);
                    } else {
                        data.files.forEach(file => {
                            const row = document.createElement('tr');
                            row.innerHTML = `
                                <td>${file.filename}</td>
                                <td>${formatDateTime(file.created_at)}</td> 
                                <td>${(file.size / (1024 * 1024)).toFixed(2)} MB</td>
                                <td>
                                    <button type="button" class="select-file" data-filename="${file.filename}">Seleccionar</button>
                                    <button type="button" class="delete-file" style="background-color: #d33" data-filename="${file.filename}">Eliminar</button>
                                </td>
                            `;
                            tableBody.appendChild(row);
                        });
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                });
        }

        loadBackupFiles();

        tableBody.addEventListener('click', function (e) {
            if (e.target.classList.contains('select-file')) {
                const filename = e.target.getAttribute('data-filename');
                document.getElementById('selectedFile').value = filename;

                Swal.fire({
                    title: 'Archivo Seleccionado',
                    text: `¿Deseas restaurar el archivo: ${filename}?`,
                    icon: 'info',
                    showCancelButton: true,
                    confirmButtonText: 'Sí, restaurar',
                    confirmButtonColor: '#04644b',
                    cancelButtonText: 'Cancelar',
                    cancelButtonColor: '#d33'
                }).then((result) => {
                    if (result.isConfirmed) {
                        const formData = new FormData();
                        formData.append('backup_file', filename);
                        formData.append('csrfmiddlewaretoken', document.querySelector('[name=csrfmiddlewaretoken]').value);

                        fetch('{% url "app:restaurar_backup" %}', {
                            method: 'POST',
                            body: formData
                        })
                            .then(response => response.json())
                            .then(data => {
                                if (data.success) {
                                    Swal.fire({
                                        title: 'Éxito',
                                        text: data.messages.join(' '),
                                        icon: 'success',
                                        confirmButtonText: 'Aceptar',
                                        confirmButtonColor: '#04644b',
                                    });
                                } else {
                                    Swal.fire({
                                        title: 'Error',
                                        text: data.messages.join(' '),
                                        icon: 'error',
                                        confirmButtonText: 'Aceptar',
                                        confirmButtonColor: '#04644b',
                                    });
                                }
                            })
                            .catch(error => {
                                console.error('Error:', error);
                                Swal.fire({
                                    title: 'Error',
                                    text: 'Ocurrió un error inesperado.',
                                    icon: 'error'
                                });
                            });
                    }
                });
            } else if (e.target.classList.contains('delete-file')) {
                const filename = e.target.getAttribute('data-filename');

                Swal.fire({
                    title: 'Confirmar Eliminación',
                    text: `¿Desea eliminar el archivo: ${filename}?`,
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Sí, eliminar',
                    confirmButtonColor: '#04644b',
                    cancelButtonText: 'Cancelar',
                    cancelButtonColor: '#d33'
                }).then((result) => {
                    if (result.isConfirmed) {
                        fetch('{% url "app:eliminar_backup" %}', {
                            method: 'POST',
                            headers: {
                                'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
                                'Content-Type': 'application/x-www-form-urlencoded'
                            },
                            body: new URLSearchParams({ 'filename': filename })
                        })
                            .then(response => response.json())
                            .then(data => {
                                Swal.fire({
                                    title: data.success ? 'Eliminado' : 'Error',
                                    text: data.messages.join(' '),
                                    icon: data.success ? 'success' : 'error',
                                    confirmButtonText: 'Aceptar',
                                    confirmButtonColor: '#04644b',
                                });

                                if (data.success) {
                                    loadBackupFiles();
                                }
                            })
                            .catch(error => {
                                console.error('Error:', error);
                                Swal.fire({
                                    title: 'Error',
                                    text: 'Ocurrió un error al intentar eliminar el archivo.',
                                    icon: 'error'
                                });
                            });
                    }
                });
            }
        });

        document.getElementById('backupForm').addEventListener('submit', function (e) {
            e.preventDefault();

            let formData = new FormData(this);

            fetch('{% url "app:gestionar_backups" %}', {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                }
            })
                .then(response => response.json())
                .then(data => {
                    const message = data.messages.join(" ");
                    Swal.fire({
                        title: data.success ? 'Éxito' : 'Error',
                        text: message,
                        icon: data.success ? 'success' : 'error',
                        confirmButtonText: 'Aceptar',
                        confirmButtonColor: '#04644b'
                    });
                    loadBackupFiles();
                })
                .catch(error => {
                    console.error('Error:', error);
                    Swal.fire({
                        title: 'Error',
                        text: 'Error al crear el respaldo.',
                        icon: 'error',
                        confirmButtonText: 'Aceptar',
                        confirmButtonColor: '#04644b'
                    });
                });
        });
    });
</script>
{% endblock %}