app/urls.py
from django.urls import path
from app.views import *
from app.views.categoria.views import *
from app.views.marca.views import *
from app.views.presentacion.views import *
from app.views.producto.views import *
from app.views.cliente.views import *
from app.views.mesero.views import *
from app.views.plato.views import *
from app.views.administrador.views import *
from app.views.operador.views import *
from app.views.venta.views import *
from app.views.detalle_venta.views import *
from app.views.cuenta.views import *
from app.views.reportes.viewsExcel import *
from app.views.reportes.viewsPDF import *
from app.views.reportes.views import *
from backups.views import BackupDatabaseView, RestoreDatabaseView, DeleteBackupView, BackupListView

app_name = 'app'
urlpatterns = [
    ### CRUD CATEGORÍA ###
    path('categoria/listar/', CategoriaListView.as_view(), name='categoria_lista'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria_crear'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_editar'),
    path('categoria/eliminar/<int:pk>/', CategoriaDeleteView.as_view(), name='categoria_eliminar'),

    ### CRUD MARCA ###
    path('marca/listar/', MarcaListView.as_view(), name='marca_lista'),
    path('marca/crear/', MarcaCreateView.as_view(), name='marca_crear'),
    path('marca/editar/<int:pk>/', MarcaUpdateView.as_view(), name='marca_editar'),
    path('marca/eliminar/<int:pk>/', MarcaDeleteView.as_view(), name='marca_eliminar'),

    ### CRUD PRESENTACIÓN ###
    path('presentacion/listar/', PresentacionListView.as_view(), name='presentacion_lista'),
    path('presentacion/crear/', PresentacionCreateView.as_view(), name='presentacion_crear'),
    path('presentacion/editar/<int:pk>/', PresentacionUpdateView.as_view(), name='presentacion_editar'),
    path('presentacion/eliminar/<int:pk>/', PresentacionDeleteView.as_view(), name='presentacion_eliminar'),

    ### CRUD PRODUCTO ###
    path('producto/listar/', ProductoListView.as_view(), name='producto_lista'),
    path('producto/crear/', ProductoCreateView.as_view(), name='producto_crear'),
    path('producto/editar/<int:pk>/', ProductoUpdateView.as_view(), name='producto_editar'),
    path('producto/eliminar/<int:pk>/', ProductoDeleteView.as_view(), name='producto_eliminar'),

    ### CRUD CLIENTE ###
    path('cliente/listar/', ClienteListView.as_view(), name='cliente_lista'),
    path('cliente/crear/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('cliente/editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editar'),
    path('cliente/eliminar/<int:pk>/', ClienteDeleteView.as_view(), name='cliente_eliminar'),
    
    ### CRUD MESERO ###
    path('mesero/listar/', MeseroListView.as_view(), name='mesero_lista'),
    path('mesero/crear/', MeseroCreateView.as_view(), name='mesero_crear'),
    path('mesero/editar/<int:pk>/', MeseroUpdateView.as_view(), name='mesero_editar'),
    path('mesero/eliminar/<int:pk>/', MeseroDeleteView.as_view(), name='mesero_eliminar'),

    ### CRUD PLATO ###
    path('plato/listar/', PlatoListView.as_view(), name='plato_lista'),
    path('plato/crear/', PlatoCreateView.as_view(), name='plato_crear'),
    path('plato/editar/<int:pk>/', PlatoUpdateView.as_view(), name='plato_editar'),
    path('plato/eliminar/<int:pk>/', PlatoDeleteView.as_view(), name='plato_eliminar'),
    
    ### CRUD ADMINISTRADOR ###
    path('administrador/listar/', AdministradorListView.as_view(), name='administrador_lista'),
    path('administrador/crear/', AdministradorCreateView.as_view(), name='administrador_crear'),
    path('administrador/editar/<int:pk>/', AdministradorUpdateView.as_view(), name='administrador_editar'),
    path('administrador/eliminar/<int:pk>/', AdministradorDeleteView.as_view(), name='administrador_eliminar'),

    ### CRUD OPERADOR ###
    path('operador/listar/', OperadorListView.as_view(), name='operador_lista'),
    path('operador/crear/', OperadorCreateView.as_view(), name='operador_crear'),
    path('operador/editar/<int:pk>/', OperadorUpdateView.as_view(), name='operador_editar'),
    path('operador/eliminar/<int:pk>/', OperadorDeleteView.as_view(), name='operador_eliminar'),
    
    ### CRUD VENTA ###
    path('venta/listar/', VentaListView.as_view(), name='venta_lista'),
    path('venta/crear/', VentaCreateView.as_view(), name='venta_crear'),
    path('venta/editar/<int:pk>/', VentaUpdateView.as_view(), name='venta_editar'),
    path('venta/eliminar/<int:pk>/', VentaDeleteView.as_view(), name='venta_eliminar'),
    path('venta/opciones/', ventas_view, name='venta_opciones'),

    ### DETALLE VENTA ###
    path('detalle_venta/listar/', DetalleVentaListView.as_view(), name='detalle_venta_lista'),
    path('detalleventa/eliminar/<int:pk>/', DetalleVentaDeleteView.as_view(), name='detalle_venta_eliminar'),

    ### CUENTA ###
    path('cuenta/listar/', CuentaListView.as_view(), name='cuenta_lista'),
    path('cuenta/crear/', CuentaCreateView.as_view(), name='cuenta'),

    ### COPIA DE SEGURIDAD DE BASE DE DATOS ###
    path('gestionar_backups/', BackupDatabaseView.as_view(), name='gestionar_backups'),
    path('restaurar_backup/', RestoreDatabaseView.as_view(), name='restaurar_backup'),
    path('eliminar-backup/', DeleteBackupView.as_view(), name='eliminar_backup'),
    path('backup_list/', BackupListView.as_view(), name='backup_list'),

    ### REPORTES ###
    path('gestion_reportes/', reporte_selector, name='gestion_reportes'),
    path('reportes/categorias/excel/', export_categorias_excel, name='export_categorias_excel'),
    path('reportes/marcas/excel/', export_marcas_excel, name='export_marcas_excel'),
    path('reportes/presentaciones/excel/', export_presentaciones_excel, name='export_presentaciones_excel'),
    path('reportes/productos/excel/', export_productos_excel, name='export_productos_excel'),
    path('reportes/platos/excel/', export_platos_excel, name='export_platos_excel'),
    path('reportes/meseros/excel/', export_meseros_excel, name='export_meseros_excel'),
    path('reportes/clientes/excel/', export_clientes_excel, name='export_clientes_excel'),
    path('reportes/administradores/excel/', export_administradores_excel, name='export_administradores_excel'),
    path('reportes/operadores/excel/', export_operadores_excel, name='export_operadores_excel'),
    path('reportes/categorias/pdf/', export_categorias_pdf, name='export_categorias_pdf'),
    path('reportes/marcas/pdf/', export_marcas_pdf, name='export_marcas_pdf'),
    path('reportes/presentaciones/pdf/', export_presentaciones_pdf, name='export_presentaciones_pdf'),
    path('reportes/productos/pdf/', export_productos_pdf, name='export_productos_pdf'),
    path('reportes/platos/pdf/', export_platos_pdf, name='export_platos_pdf'),
    path('reportes/meseros/pdf/', export_meseros_pdf, name='export_meseros_pdf'),
    path('reportes/clientes/pdf/', export_clientes_pdf, name='export_clientes_pdf'),
    path('reportes/administradores/pdf/', export_administradores_pdf, name='export_administradores_pdf'),
    path('reportes/operadores/pdf/', export_operadores_pdf, name='export_operadores_pdf'),

        ### API´S ###
    path('venta/productos_api/', productos_api, name='productos_api'),
    path('venta/platos_api/', platos_api, name='platos_api'),
    path('venta/clientes_api/', clientes_api, name='clientes_api'),
    path('venta/meseros_api/', meseros_api, name='meseros_api'),
    path('venta/crear_cliente_ajax/', crear_cliente_ajax, name='crear_cliente_ajax'),
]

asuan/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio.views import indexView
from login.views import *
from app.views import *
from dashboard.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', indexView.as_view(), name='index'),
    path('dashboard', dashView.as_view(), name='dashboard'),
    path('login', include('login.urls')),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='register/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='register/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_confirm.html'), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'), name='password_reset_complete'),
]

app/views/presentacion/views.py
from django.contrib import messages
import django
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
import os
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.db.models import ProtectedError
from app.models import Presentacion
from app.forms import PresentacionForm

@method_decorator(never_cache, name='dispatch')
def lista_presentacion(request):
    nombre = {
        'titulo': 'Listado de presentaciones',
        'presentaciones': Presentacion.objects.all()
    }
    return render(request, 'presentacion/listar.html',nombre)

###### LISTAR ######

@method_decorator(never_cache, name='dispatch')
class PresentacionListView(ListView):
    model = Presentacion
    template_name = 'presentacion/listar.html'
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        nombre = {'nombre': 'Juan'}
        return JsonResponse(nombre)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Listado de presentaciones'
        context['entidad'] = 'Listado de presentaciones'
        context['listar_url'] = reverse_lazy('app:presentacion_lista')
        context['crear_url'] = reverse_lazy('app:presentacion_crear')
        return context

###### CREAR ######

@method_decorator(never_cache, name='dispatch')
class PresentacionCreateView(CreateView):
    model = Presentacion
    form_class = PresentacionForm
    template_name = 'presentacion/crear.html'
    success_url = reverse_lazy('app:presentacion_lista')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Registrar presentación'
        context['entidad'] = 'Registrar presentación'
        context['error'] = 'Esta presentación ya existe'
        context['listar_url'] = reverse_lazy('app:presentacion_lista')
        context['created'] = self.request.session.pop('created', False) 
        return context
    
    def form_valid(self, form):
        presentacion = form.cleaned_data.get('presentacion').lower()
        unidad_medida = form.cleaned_data.get('unidad_medida')

        # Verifica si ya existe una combinación de presentación y unidad de medida
        if Presentacion.objects.filter(presentacion__iexact=presentacion, unidad_medida=unidad_medida).exists():
            form.add_error('presentacion', 'Ya existe una presentación registrada con ese nombre y unidad de medida.')
            return self.form_invalid(form)

        response = super().form_valid(form)
        success_url = reverse('app:presentacion_crear') + '?created=True'
        return redirect(success_url)
        
###### EDITAR ######

@method_decorator(never_cache, name='dispatch')
class PresentacionUpdateView(UpdateView):
    model = Presentacion
    form_class = PresentacionForm
    template_name = 'presentacion/crear.html'
    success_url = reverse_lazy('app:presentacion_lista')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Editar presentación'
        context['entidad'] = 'Editar presentación'
        context['error'] = 'Esta presentación ya existe'
        context['listar_url'] = reverse_lazy('app:presentacion_lista')
        return context
    
    def form_valid(self, form):
        presentacion = form.cleaned_data.get('presentacion').lower()
        response = super().form_valid(form)
        success_url = reverse('app:presentacion_crear') + '?updated=True'
        return redirect(success_url)

###### ELIMINAR ######

@method_decorator(never_cache, name='dispatch')
class PresentacionDeleteView(DeleteView):
    model = Presentacion
    template_name = 'presentacion/eliminar.html'
    success_url = reverse_lazy('app:presentacion_lista')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Eliminar presentación'
        context['entidad'] = 'Eliminar presentación'
        context['listar_url'] = reverse_lazy('app:presentacion_lista')
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            return JsonResponse({'success': True, 'message': 'Presentación eliminada con éxito.'})
        except ProtectedError:
            return JsonResponse({'success': False, 'message': 'No se puede eliminar la presentación porque está asociada a un producto.'})

app/templates/presentacion/crear.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block contenido %}
<form method="post" action=".">
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-plus"></i>
                {{titulo}}
            </h3>
        </div>
        <div class="card-body">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="text">{{ field.label }}:</label>
                {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="card-footer">
        <button class="btn btn-primary btn-flat"><i class="fas fa-plus"></i> Guardar</button>
        <a href="{{ listar_url }}" class="btn btn-danger btn-flat">
            <i class="fas fa-times"></i> Cancelar
        </a>
    </div>
    </div>
</form>
<script>
    {% if form.errors %}
    var errors = '';
    {% for field in form %}
    {% for error in field.errors %}
    errors += '{{ error }}';
    {% endfor %}
    {% endfor %}

    Swal.fire({
        title: 'Error',
        text: 'Ya existe una presentación con este nombre.',
        icon: 'error',
        confirmButtonText: 'Aceptar',
        confirmButtonColor: '#04644b'
    });
    {% elif request.GET.created %}
    Swal.fire({
        title: 'Éxito',
        text: 'Presentación registrada con éxito.',
        icon: 'success',
        confirmButtonText: 'Aceptar',
        confirmButtonColor: '#04644b'
    }).then((result) => {
        if (result.isConfirmed) {
            window.location.href = "{% url 'app:presentacion_lista' %}";
        }
    });
    {% elif request.GET.updated %}
    Swal.fire({
        title: 'Éxito',
        text: 'Presentación editada con éxito.',
        icon: 'success',
        confirmButtonText: 'Aceptar',
        confirmButtonColor: '#04644b'
    }).then((result) => {
        if (result.isConfirmed) {
            window.location.href = "{% url 'app:presentacion_lista' %}";
        }
    });
    {% endif %}
</script>
{% endblock %}

app/templates/presentacion/listar.html
{% extends 'listar.html' %}

{% block columnas %}
<tr>
    <th scope="col">id</th>
    <th scope="col">Presentación</a></th>
    <th scope="col">Estado</th>
    <th scope="col">Opciones</th>
</tr>
{% endblock %}

{% block filas %}
{% for p in object_list %}
<tr>
    <td>{{ p.id }}</td>
    <td>{{ p.presentacion }} {{ p.get_unidad_medida_display }}</td>
    <td>{{ p.estado | yesno:"Activo,Inactivo" }}</td>
    <td>
        <a href="{% url 'app:presentacion_editar' p.id %}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i></a>
        <a href="{% url 'app:presentacion_eliminar' p.id %}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a>
    </td>
</tr>
{% endfor %}
{% endblock %}
{% block javascript %}
<script type="application/javascript">
    $(document).ready(function () {
        $("#tabla").DataTable({
            responsive: true,
            initComplete: function () {
                var api = this.api();
                var columnNames = ['id', 'Presentacion', 'Estado', 'Opciones'];
                var excludedColumnIndex = columnNames.indexOf('Opciones');
                api.columns().every(function (index) {
                    var column = this;
                    var header = $(column.header());
                    if (index !== excludedColumnIndex) {
                        var filterContainer = $('<div class="filter-container"></div>').appendTo(header.empty());
                        $('<label>' + columnNames[index] + '</label>').appendTo(filterContainer);
                        var select = $('<select><option value="">Todos</option></select>')
                            .appendTo(filterContainer)
                            .on('change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });
                        column.data().unique().sort().each(function (d, j) {
                            select.append('<option value="' + d + '">' + d + '</option>');
                        });
                    } else {
                        $('<label>' + columnNames[index] + '</label>').appendTo(header.empty());
                    }
                });
            }
        });
    });
</script>
{% endblock %}