app/urls.py
from django.urls import path
from app.views import *
from app.views.categoria.views import *
from app.views.marca.views import *
from app.views.presentacion.views import *
from app.views.producto.views import *
from app.views.cliente.views import *
from app.views.mesero.views import *
from app.views.plato.views import *
from app.views.administrador.views import *
from app.views.operador.views import *
from app.views.venta.views import *
from app.views.detalle_venta.views import *
from app.views.cuenta.views import *
from app.views.reportes.viewsExcel import *
from app.views.reportes.viewsPDF import *
from app.views.reportes.views import *
from backups.views import BackupDatabaseView, RestoreDatabaseView, DeleteBackupView, BackupListView

app_name = 'app'
urlpatterns = [
    ### CRUD CATEGORÍA ###
    path('categoria/listar/', CategoriaListView.as_view(), name='categoria_lista'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria_crear'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_editar'),
    path('categoria/eliminar/<int:pk>/', CategoriaDeleteView.as_view(), name='categoria_eliminar'),

    ### CRUD MARCA ###
    path('marca/listar/', MarcaListView.as_view(), name='marca_lista'),
    path('marca/crear/', MarcaCreateView.as_view(), name='marca_crear'),
    path('marca/editar/<int:pk>/', MarcaUpdateView.as_view(), name='marca_editar'),
    path('marca/eliminar/<int:pk>/', MarcaDeleteView.as_view(), name='marca_eliminar'),

    ### CRUD PRESENTACIÓN ###
    path('presentacion/listar/', PresentacionListView.as_view(), name='presentacion_lista'),
    path('presentacion/crear/', PresentacionCreateView.as_view(), name='presentacion_crear'),
    path('presentacion/editar/<int:pk>/', PresentacionUpdateView.as_view(), name='presentacion_editar'),
    path('presentacion/eliminar/<int:pk>/', PresentacionDeleteView.as_view(), name='presentacion_eliminar'),

    ### CRUD PRODUCTO ###
    path('producto/listar/', ProductoListView.as_view(), name='producto_lista'),
    path('producto/crear/', ProductoCreateView.as_view(), name='producto_crear'),
    path('producto/editar/<int:pk>/', ProductoUpdateView.as_view(), name='producto_editar'),
    path('producto/eliminar/<int:pk>/', ProductoDeleteView.as_view(), name='producto_eliminar'),

    ### CRUD CLIENTE ###
    path('cliente/listar/', ClienteListView.as_view(), name='cliente_lista'),
    path('cliente/crear/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('cliente/editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editar'),
    path('cliente/eliminar/<int:pk>/', ClienteDeleteView.as_view(), name='cliente_eliminar'),
    
    ### CRUD MESERO ###
    path('mesero/listar/', MeseroListView.as_view(), name='mesero_lista'),
    path('mesero/crear/', MeseroCreateView.as_view(), name='mesero_crear'),
    path('mesero/editar/<int:pk>/', MeseroUpdateView.as_view(), name='mesero_editar'),
    path('mesero/eliminar/<int:pk>/', MeseroDeleteView.as_view(), name='mesero_eliminar'),

    ### CRUD PLATO ###
    path('plato/listar/', PlatoListView.as_view(), name='plato_lista'),
    path('plato/crear/', PlatoCreateView.as_view(), name='plato_crear'),
    path('plato/editar/<int:pk>/', PlatoUpdateView.as_view(), name='plato_editar'),
    path('plato/eliminar/<int:pk>/', PlatoDeleteView.as_view(), name='plato_eliminar'),
    
    ### CRUD ADMINISTRADOR ###
    path('administrador/listar/', AdministradorListView.as_view(), name='administrador_lista'),
    path('administrador/crear/', AdministradorCreateView.as_view(), name='administrador_crear'),
    path('administrador/editar/<int:pk>/', AdministradorUpdateView.as_view(), name='administrador_editar'),
    path('administrador/eliminar/<int:pk>/', AdministradorDeleteView.as_view(), name='administrador_eliminar'),

    ### CRUD OPERADOR ###
    path('operador/listar/', OperadorListView.as_view(), name='operador_lista'),
    path('operador/crear/', OperadorCreateView.as_view(), name='operador_crear'),
    path('operador/editar/<int:pk>/', OperadorUpdateView.as_view(), name='operador_editar'),
    path('operador/eliminar/<int:pk>/', OperadorDeleteView.as_view(), name='operador_eliminar'),
    
    ### CRUD VENTA ###
    path('venta/listar/', VentaListView.as_view(), name='venta_lista'),
    path('venta/crear/', VentaCreateView.as_view(), name='venta_crear'),
    path('venta/editar/<int:pk>/', VentaUpdateView.as_view(), name='venta_editar'),
    path('venta/eliminar/<int:pk>/', VentaDeleteView.as_view(), name='venta_eliminar'),
    path('venta/opciones/', ventas_view, name='venta_opciones'),

    ### DETALLE VENTA ###
    path('detalle_venta/listar/', DetalleVentaListView.as_view(), name='detalle_venta_lista'),
    path('detalleventa/eliminar/<int:pk>/', DetalleVentaDeleteView.as_view(), name='detalle_venta_eliminar'),

    ### CUENTA ###
    path('cuenta/listar/', CuentaListView.as_view(), name='cuenta_lista'),
    path('cuenta/crear/', CuentaCreateView.as_view(), name='cuenta'),

    ### COPIA DE SEGURIDAD DE BASE DE DATOS ###
    path('gestionar_backups/', BackupDatabaseView.as_view(), name='gestionar_backups'),
    path('restaurar_backup/', RestoreDatabaseView.as_view(), name='restaurar_backup'),
    path('eliminar-backup/', DeleteBackupView.as_view(), name='eliminar_backup'),
    path('backup_list/', BackupListView.as_view(), name='backup_list'),

    ### REPORTES ###
    path('gestion_reportes/', reporte_selector, name='gestion_reportes'),
    path('reportes/categorias/excel/', export_categorias_excel, name='export_categorias_excel'),
    path('reportes/marcas/excel/', export_marcas_excel, name='export_marcas_excel'),
    path('reportes/presentaciones/excel/', export_presentaciones_excel, name='export_presentaciones_excel'),
    path('reportes/productos/excel/', export_productos_excel, name='export_productos_excel'),
    path('reportes/platos/excel/', export_platos_excel, name='export_platos_excel'),
    path('reportes/meseros/excel/', export_meseros_excel, name='export_meseros_excel'),
    path('reportes/clientes/excel/', export_clientes_excel, name='export_clientes_excel'),
    path('reportes/administradores/excel/', export_administradores_excel, name='export_administradores_excel'),
    path('reportes/operadores/excel/', export_operadores_excel, name='export_operadores_excel'),
    path('reportes/categorias/pdf/', export_categorias_pdf, name='export_categorias_pdf'),
    path('reportes/marcas/pdf/', export_marcas_pdf, name='export_marcas_pdf'),
    path('reportes/presentaciones/pdf/', export_presentaciones_pdf, name='export_presentaciones_pdf'),
    path('reportes/productos/pdf/', export_productos_pdf, name='export_productos_pdf'),
    path('reportes/platos/pdf/', export_platos_pdf, name='export_platos_pdf'),
    path('reportes/meseros/pdf/', export_meseros_pdf, name='export_meseros_pdf'),
    path('reportes/clientes/pdf/', export_clientes_pdf, name='export_clientes_pdf'),
    path('reportes/administradores/pdf/', export_administradores_pdf, name='export_administradores_pdf'),
    path('reportes/operadores/pdf/', export_operadores_pdf, name='export_operadores_pdf'),

        ### API´S ###
    path('venta/productos_api/', productos_api, name='productos_api'),
    path('venta/platos_api/', platos_api, name='platos_api'),
    path('venta/clientes_api/', clientes_api, name='clientes_api'),
    path('venta/meseros_api/', meseros_api, name='meseros_api'),
    path('venta/crear_cliente_ajax/', crear_cliente_ajax, name='crear_cliente_ajax'),
]

asuan/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio.views import indexView
from login.views import *
from app.views import *
from dashboard.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', indexView.as_view(), name='index'),
    path('dashboard', dashView.as_view(), name='dashboard'),
    path('login', include('login.urls')),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='register/password_reset_form.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='register/password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='register/password_reset_confirm.html'), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='register/password_reset_complete.html'), name='password_reset_complete'),
]

app/templates/aside/body.html
{% extends 'home.html' %}
{% load static %}
{% block body %}

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper" style="display: grid; grid-template-rows: auto 1fr">
        {% include 'aside/header.html' %}
        {% include 'aside/sidebar.html' %}
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="{{listar_url}}">{{entidad}}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block contenido %}
                    {% endblock %}
                </div>
            </div>
        </div>
        {% include 'footer.html' %}
    </div>
    {% block javascript %}
    {% endblock %}
</body>
{% endblock %}

app/templates/aside/header.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-dark navbar-green">
    <ul class="navbar-nav">
        <li class="nav-itemmm">
            <a class="nav-link" id="toggle-menu" data-widget="pushmenu" href="#" role="button">
                <i class="fas fa-bars" style="color: white; font-size: 30px; text-shadow: 3px 3px 2.5px black;"></i>
            </a>
        </li>
        <li class="nav-itemmm d-none d-sm-inline-block ">
            <a href="{% url 'dashboard' %}" class="nav-link text-white"
                style="font-size: 20px; font-style: oblique; text-shadow: 3px 3px 2.5px black;">Inicio</a>
        </li>
    </ul>
    <div class="container">
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
        </div>
    </div>
    <span class="icon" id="logo">
        <img src="{% static 'img/icon.png' %}" alt="Logo palmera">
    </span>
    <div class="col-sm-6">
        <h1 class="m-0" style="font-size: 50px; font-style: oblique; color: white; text-shadow: 3px 3px 2.5px black;">Panel de administración</h1>
    </div>
    <ul class="navbar-nav ml-auto">
        <li class="nav-itemmm">
            <a class="nav-link" href="">
                <i id="darkModeToggle" class="fas fa-moon" title="Modo oscuro-claro"
                    style="font-size: 30px; color: white; text-shadow: 3px 3px 2.5px black;" aria-hidden="true"
                    onclick="toggleDarkMode()"></i>
            </a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-itemmm">
            <a class="nav-link" href="{% static 'resources/Manual de usuario (Software G&V Asuán).pdf' %}" target="_blank">
                <i class="fas fa-question" title="Ayuda"
                    style="font-size: 30px; color: white; text-shadow: 3px 3px 2.5px black;" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
    {% if perms.app.view_usuario %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-itemmm">
            <a class="nav-link" href="{% url 'app:gestionar_backups'%}">
                <i class="fas fa-database" title="Administrar copias de seguridad"
                    style="font-size: 30px; color: white; text-shadow: 3px 3px 2.5px black;" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
    {% endif %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-itemmm dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user" style="font-size: 30px; color: white; text-shadow: 3px 3px 2.5px black;"></i>
            </a>
            <div class="logout-menu dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <span class="dropdown-item" style="color: white">Usuario activo:<br>{{ user.username }}</span>
                <a class="dropdown-item" style="color: white" href="#" onclick="confirmLogout(event)">Cerrar sesión</a>
            </div>
        </li>
    </ul>
</nav>
<script src="{% static 'lib/sweetalert2/sweetHeader.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        function toggleDarkMode() {
            document.body.classList.toggle('dark-mode');
            const isDarkMode = document.body.classList.contains('dark-mode');
            const darkModeIcon = document.getElementById("darkModeToggle");

            localStorage.setItem('dark-mode', isDarkMode);

            if (isDarkMode) {
                darkModeIcon.classList.remove('fa-moon');
                darkModeIcon.classList.add('fa-sun');
            } else {
                darkModeIcon.classList.remove('fa-sun');
                darkModeIcon.classList.add('fa-moon');
            }
        }
        if (localStorage.getItem('dark-mode') === 'true') {
            document.body.classList.add('dark-mode');
            const darkModeIcon = document.getElementById("darkModeToggle");
            darkModeIcon.classList.remove('fa-moon');
            darkModeIcon.classList.add('fa-sun');
        }
        window.toggleDarkMode = toggleDarkMode;
    });

    function confirmLogout(event) {
        event.preventDefault();
        Swal.fire({
            title: '¿Desea cerrar sesión?',
            text: "",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#04644b',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sí, cerrar sesión',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = "{% url 'logout' %}";
            }
        });
    }
</script>

app/templates/aside/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-collapse elevation-2">
    <div class="sidebar">
        <div class="logo-container text-center">
            <img src="{% static 'img/logo_asuan3.png' %}" alt="Logo Asuán" class="logo-image img-fluid">
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" role="menu" data-accordion="false">
                <h1 style="font-size: 50px; font-style: oblique; color: white; text-align: center">ㅤ</h1>
                <li class="nav-itemm">
                    <a href="#submenu1" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-shopping-cart" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Gestión de ventas</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu1">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:venta_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-search" style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Consultar ventas</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:venta_crear' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-cash-register" style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Ventas por caja</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:cuenta' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-file-invoice-dollar" style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Ventas por cuenta</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-itemm">
                    <a href="#submenu2" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-dolly" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Gestión de productos</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu2">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:producto_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-list"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Lista de productos</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:producto_crear' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-plus"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Registrar producto</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:categoria_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-tag"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Categorias</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:marca_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-project-diagram"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Marcas</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:presentacion_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-shapes"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Presentaciones</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-itemm">
                    <a href="#submenu3" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-drumstick-bite" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Gestión de restaurante</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu3">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:plato_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-list"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Lista de platos</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:plato_crear' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-plus"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Registrar plato</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-itemm">
                    <a href="#submenu4" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-user-friends" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Gestión de meseros</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu4">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:mesero_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-list"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Lista de meseros</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:mesero_crear' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-plus"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Registrar mesero</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-itemm">
                    <a href="#submenu5" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-users" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Gestión de clientes</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu5">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:cliente_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-list"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Lista de clientes</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:cliente_crear' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-plus"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Registrar cliente</span>
                            </a>
                        </li>
                    </ul>
                </li>
                {% if perms.app.view_usuario %}
                <li class="nav-itemm">
                    <a href="#submenu7" class="nav-link d-flex justify-content-between align-items-center"
                        data-toggle="collapse" aria-expanded="false" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-user-cog" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Gestión de usuarios</p>
                        </div>
                    </a>
                    <ul class="collapse list-unstyled pl-4" id="submenu7">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:administrador_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-user-shield"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Administradores</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="{% url 'app:operador_lista' %}"
                                style="font-size: 19px; color: white;">
                                <i class="nav-icon fas fa-user-alt"
                                    style="font-size: 20px; margin-right: 10px; color: white;"></i>
                                <span>Operadores</span>
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}
                <li class="nav-itemm">
                    <a href="{% url 'app:gestion_reportes' %}" class="nav-link d-flex justify-content-between align-items-center" style="color: white; font-size: 13px;">
                        <div class="d-flex align-items-center">
                            <i class="nav-icon fas fa-file-pdf" style="font-size: 25px; margin-right: 10px;"></i>
                            <p class="mb-0" style="font-size: 19px;">Reportes</p>
                        </div>
                    </a>                    
                </li>
            </ul>
        </nav>
    </div>
</aside>
<script>
    $(document).ready(function () {
        $("#toggle-menu").click(function (e) {
            e.preventDefault();
            $(".logo-image").toggle();
        });
    });
    function delayCollapse(id) {
        setTimeout(function () {
            $(id).collapse('hide');
        }, 3000);
    }    
</script>